# Generated by Django 3.2.8 on 2021-11-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos_string',
            field=models.CharField(default='[]', max_length=999999, verbose_name='Favoritos'),
        ),
    ]
