# Generated by Django 3.2.7 on 2021-10-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url_catalogo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MangaPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('enlace_img', models.URLField()),
                ('enlace_manga', models.URLField()),
                ('generos', models.ManyToManyField(to='mangas.Genero')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mangas.mangapreview')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangas.manga'),
        ),
    ]
